apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: flask-pod
  labels:
    k8s-app: my-flask
    type: flask1
spec:
  selector:
    matchLabels:
      name: my-flask
  template:
    metadata:
      labels:
        name: my-flask
    spec:
      hostNetwork: true
      containers:
        - name: my-flask
          image: rasp-flask2
          imagePullPolicy: Never
          command: [ "bash", "/usr/local/bin/start"]
          ports:
            - name: my-flask
              containerPort: 8080
              hostPort: 8080
              protocol: TCP

